repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: mise run lint
        language: system
        pass_filenames: false
      - id: test
        name: test
        entry: mise run test
        language: system
        pass_filenames: false
